export interface GearItem {
  id: string;
  name: string;
  category: "Camera" | "Lens" | "Lighting" | "Audio" | "Support" | "Bundle";
  price12h: number;
  price24h: number;
  image: string;
  specs: string[];
  description: string;
  details?: string[];
  available: boolean;
}

export const inventory: GearItem[] = [
  {
    id: "sony-fx6",
    name: "Sony FX6",
    category: "Camera",
    price12h: 400000,
    price24h: 600000,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBdaKUtpAPxKY0Qav2aDdbwoet57IjiTCoyi6m3zlq4BC4EHgf7o6ocSnhI40_XV2pOaKYADX0CUBOOOht1BT3wOq5C0tuqqkIkQwY5-oSyVIlK_6LaNwtjfq2UraaIJV4146PadRZge93QEeZXW--jpAxglTrAJGhqMGrIG4NiHdZ5P9ToK7Ge_lO0ovqrYWyDznkB0-CRPmaGxQHp7h3gIUJdIEbWJ3brtGrrcR228NYAIt5qtXk8",
    specs: ["Full-Frame", "4K 120p 10-bit"],
    description: "Professional cinema line camera with built-in ND filters.",
    details: [
      "Sistem autofokus mewarisi teknologi mutakhir, menampilkan pelacakan real-time bahkan saat merekam video. Prosesor yang responsif memastikan operasi tanpa lag, krusial untuk menangkap momen tak terduga dalam berbagai skenario produksi.",
      "Bagi para profesional, alat ini adalah powerhouse sejati. Menawarkan resolusi luar biasa dan reproduksi warna yang menakjubkan, menjadikannya pilihan ideal untuk komersial dan dokumenter tanpa perlu color grading yang berat.",
      "Layar fleksibel untuk berbagai sudut perekaman yang dinamis.",
      "Konektivitas canggih dengan kecepatan tinggi untuk alur kerja profesional.",
      "Desain bodi tahan debu dan kelembapan untuk kondisi lapangan yang menantang."
    ],
    available: true,
  },
  {
    id: "red-komodo",
    name: "RED Komodo 6K",
    category: "Camera",
    price12h: 550000,
    price24h: 800000,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCQlYJafOktfF4msLqdXCYpZoT7Jm29nuoL2Bbip55fXbSZlQipvnLQ1AEIhGX8GcDK9Hyv866JERWKV8suzOjCJkO46Ftv1FZ90lDGi_9yr6fxRmvwzubegsPAfYDgA38hwyVcW1GfBTztI6opCnmG9WmeUnbUFx-hC2y7zmYv9wCVXhtu6hgwaYU39421RKItLECIE7zd9Ph7flBIIf2izhrmkspxDZmKMyvPpSVuGm72eYeqV0YW",
    specs: ["6K Global Shutter", "REDCODE RAW"],
    description: "Compact cinema camera capable of stunning RED raw footage.",
    available: true,
  },
  {
    id: "arri-alexa",
    name: "ARRI Alexa Mini",
    category: "Camera",
    price12h: 1000000,
    price24h: 1500000,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDLDh1yv3wLXBOrkea_og-DjlVCoLSFt8JpM0vPasQL7vNYSPA8y18IZZKvRabxALP-VmnE558ZFm_t54D9ljDZoy0iAe3Z0cmcl_LsQ-NM3R1ic7nmtp85_p7hIWv0n4900DKyfBKmkgybNkY_5ekAUp51ykB7MIFj9h5zEx1XTAwD4JEhIndnrkFx0bLhKIkk6K8fQs1XxcRja4xUGR5m7nFxkOYbHhgBmz-HOHBkx0U0aLECLbs9",
    specs: ["4.5K ARRIRAW", "ProRes 4444 XQ"],
    description: "The industry standard for high-end cinematic productions.",
    available: true,
  },
  {
    id: "sony-a7iv",
    name: "Sony A7 IV",
    category: "Camera",
    price12h: 200000,
    price24h: 300000,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop",
    specs: ["33MP Full-Frame", "4K 60p 10-bit"],
    description: "Versatile hybrid camera perfect for both photo and video.",
    available: true,
  },
  {
    id: "lens-sigma-24-70",
    name: "Sigma 24-70mm f/2.8 DG DN Art",
    category: "Lens",
    price12h: 100000,
    price24h: 150000,
    image: "https://images.unsplash.com/photo-1616423640778-28d1b53229bd?q=80&w=800&auto=format&fit=crop",
    specs: ["Sony E-Mount", "f/2.8 Constant"],
    description: "The ultimate standard zoom lens for Sony E-mount.",
    available: true,
  },
  {
    id: "light-godox-ad200",
    name: "Godox AD200 Pro",
    category: "Lighting",
    price12h: 50000,
    price24h: 75000,
    image: "https://images.unsplash.com/photo-1596700508534-7a544f128e93?q=80&w=800&auto=format&fit=crop",
    specs: ["200Ws", "TTL/HSS"],
    description: "Compact and powerful pocket flash.",
    available: true,
  },
  {
    id: "bundle-essential-wedding",
    name: "The Essential Wedding Kit",
    category: "Bundle",
    price12h: 380000,
    price24h: 500000,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAL6GsJ4OJLkuBpZ0z9e_Q_Ukm0qcMKMK21irkAKScXFTxvBmwx6SOIoWzOhAYLl5P5MdnD3OtVExlz3WUiF_teI5-rUFyle8HyW5WxfgXs2SNdpnIoC0rY-IgbkfC3BR-MzHX5H-j9YDcl_ybbUDqNX-fkhn1Vtt5GWYSwbmi6WkWm1IrHXBZKJ4G_V-Y5NHPv2wd5KxvZJX0bT33Z1-gYIGGjVNhkJW8i6uchI-f7dqhnus-eZVpp",
    specs: ["Sony A7 III Body", "Tamron 28-75mm f/2.8", "2x NP-FZ100 Batteries", "SanDisk 64GB Extreme Pro"],
    description: "Pre-configured kit for typical shoot scenarios. Save up to 15%.",
    available: true,
  },
  {
    id: "bundle-basic-lighting",
    name: "Basic Studio Lighting",
    category: "Bundle",
    price12h: 160000,
    price24h: 220000,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDNLooZazDlroYQR3pJhLx2nPA_R5PoYWIvPJpB9_7RJg62FxtZHQSg-rbivBB7pSdwc9FqAE27Xg_CruHfEiryPKMu4860B9i5AfFxb51dUk-xqRB9ySzgTVIT8Ty3BEXJFJMx2cxpx_6qGw0v9DyiU04NRfBT_rTD51bZ6ZNHK5C7TRnovP28oDcTxRmMJpGappGInTUx45Q2Vt2XJfcStfA2Sw5UrjeUWzkkD8JJ5C1CWuoukP7W",
    specs: ["2x Godox SL60W Video Light", "2x Rectangular Softbox 60x90", "2x Light Stand Takara", "Kabel Roll 10m"],
    description: "Pre-configured kit for typical shoot scenarios. Save up to 20%.",
    available: true,
  },

  // ── Synced from Abon Sewa Kamera Semarang official price list ──

  {
    id: "sony-a7-iii",
    name: "Sony A7 III",
    category: "Camera",
    price12h: 220000,
    price24h: 230000,
    image: "https://images.unsplash.com/photo-1516724562728-afc824a36e84?q=80&w=800&auto=format&fit=crop",
    specs: ["Full-Frame", "Netral & Mentah Color Science"],
    description: "The all-time favorite Sony full-frame body — fast autofocus, neutral color, and an easy-to-find E-mount lens ecosystem.",
    available: true,
  },
  {
    id: "canon-eos-r",
    name: "Canon EOS R",
    category: "Camera",
    price12h: 240000,
    price24h: 250000,
    image: "https://images.unsplash.com/photo-1606986628253-05620e9c3d43?q=80&w=800&auto=format&fit=crop",
    specs: ["Full-Frame", "Canon Skin Tone Color Science"],
    description: "Canon's first full-frame mirrorless — great skin tones and a familiar ergonomic body for all-rounder shooters.",
    available: true,
  },
  {
    id: "fujifilm-xt4",
    name: "Fujifilm X-T4",
    category: "Camera",
    price12h: 215000,
    price24h: 225000,
    image: "https://images.unsplash.com/photo-1621520291095-aa6c7137f048?q=80&w=800&auto=format&fit=crop",
    specs: ["APS-C", "5-Axis IBIS", "Film Simulation Modes"],
    description: "A compact APS-C body loved for its in-body stabilization and signature Fujifilm film-simulation color.",
    available: true,
  },
  {
    id: "lens-sony-2470-gm-i",
    name: "Sony 24-70mm GM F2.8 Mark I",
    category: "Lens",
    price12h: 225000,
    price24h: 230000,
    image: "https://images.unsplash.com/photo-1617005082133-548c4dd27f35?q=80&w=800&auto=format&fit=crop",
    specs: ["Sony FE Mount", "f/2.8 Constant", "G Master Series"],
    description: "The benchmark Sony G Master standard zoom — sharp wide open, built for weddings, events, and run-and-gun work.",
    available: true,
  },
  {
    id: "lens-tamron-2875-g2",
    name: "Tamron 28-75mm F2.8 Di III VXD G2",
    category: "Lens",
    price12h: 145000,
    price24h: 150000,
    image: "https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?q=80&w=800&auto=format&fit=crop",
    specs: ["Sony FE Mount", "f/2.8 Constant", "Fast VXD Autofocus"],
    description: "A lighter, budget-friendly alternative to the native GM zoom, with fast linear-motor autofocus.",
    available: true,
  },
  {
    id: "light-godox-sl60w-ii",
    name: "Godox SL60W II",
    category: "Lighting",
    price12h: 105000,
    price24h: 115000,
    image: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=800&auto=format&fit=crop",
    specs: ["60W COB LED", "Includes Stand & Softbox"],
    description: "A continuous LED key light that comes as a full set — light, stand, and softbox — ready to shoot straight out of the bag.",
    available: true,
  },
  {
    id: "light-aputure-600x-pro",
    name: "Aputure 600X Pro",
    category: "Lighting",
    price12h: 320000,
    price24h: 330000,
    image: "https://images.unsplash.com/photo-1560853865-2c8e1d8d2b2c?q=80&w=800&auto=format&fit=crop",
    specs: ["600W Bi-Color LED", "Includes Stand & Softbox"],
    description: "A powerful bi-color LED fixture for larger sets and daylight-balanced shoots that need real output.",
    available: false,
  },
  {
    id: "audio-rode-ntg4-plus",
    name: "Rode NTG4+",
    category: "Audio",
    price12h: 80000,
    price24h: 90000,
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=800&auto=format&fit=crop",
    specs: ["Shotgun Microphone", "Built-in Rechargeable Battery"],
    description: "A broadcast-grade shotgun mic with onboard gain control — the standard boom mic for narrative and documentary sets.",
    available: true,
  },
  {
    id: "audio-saramonic-blink-b2",
    name: "Saramonic Blink B2",
    category: "Audio",
    price12h: 65000,
    price24h: 75000,
    image: "https://images.unsplash.com/photo-1590602847861-3c1b2e6a4d1f?q=80&w=800&auto=format&fit=crop",
    specs: ["2.4GHz Wireless", "Dual Transmitter + 1 Receiver"],
    description: "A compact dual-channel wireless mic system — clip it on two presenters and go, no cables needed.",
    available: true,
  },
  {
    id: "support-dji-rs4",
    name: "DJI RS4",
    category: "Support",
    price12h: 240000,
    price24h: 250000,
    image: "https://images.unsplash.com/photo-1589872307379-0ffdf9829123?q=80&w=800&auto=format&fit=crop",
    specs: ["3-Axis Gimbal Stabilizer", "10lb Payload"],
    description: "DJI's flagship handheld gimbal for mirrorless and cinema bodies, giving smooth, stabilized handheld footage.",
    available: true,
  },

  // ── Bundle packages, priced per the official Canon/Sony x Sigma bundling sheet ──

  {
    id: "bundle-a7iii-sigma-2470",
    name: "Sony A7 III + Sigma 24-70mm Bundle",
    category: "Bundle",
    price12h: 265000,
    price24h: 275000,
    image: "https://images.unsplash.com/photo-1519638399535-1b036603ac77?q=80&w=800&auto=format&fit=crop",
    specs: ["Sony A7 III Body", "Sigma 24-70mm F2.8 DG-DN", "Ready-to-shoot All-rounder Kit"],
    description: "The most requested full-frame + standard-zoom combo, bundled at a lower combined rate than renting each piece separately.",
    available: true,
  },
  {
    id: "bundle-a6600-sigma-85",
    name: "Sony A6600 + Sigma 85mm F1.4 Bundle",
    category: "Bundle",
    price12h: 245000,
    price24h: 260000,
    image: "https://images.unsplash.com/photo-1519183071298-a2962be96f83?q=80&w=800&auto=format&fit=crop",
    specs: ["Sony A6600 APS-C Body", "Sigma 85mm F1.4 DG DN", "Great for Portraits & Interviews"],
    description: "A lightweight APS-C body paired with a fast portrait prime — ideal for interview setups and creamy background separation.",
    available: true,
  },
  {
    id: "bundle-eosr-sigma-2470",
    name: "Canon EOS R + Sigma 24-70mm Bundle",
    category: "Bundle",
    price12h: 335000,
    price24h: 350000,
    image: "https://images.unsplash.com/photo-1610555356070-d0efb6505f81?q=80&w=800&auto=format&fit=crop",
    specs: ["Canon EOS R Full-Frame Body", "Sigma 24-70mm F2.8 DG DN Art", "Full-Frame Event Kit"],
    description: "Canon's full-frame body matched with Sigma's Art-series standard zoom — a solid full-day event and commercial kit.",
    available: true,
  }
];