export const siteConfig = {
  name: "Abon Sewa Kamera",
  shortName: "Abon Kamera",
  tagline: "Rental Kamera & Peralatan Produksi Terlengkap",
  description: "Professional Camera & Production Equipment Rental in Semarang, Central Java.",
  city: "Semarang",
  province: "Jawa Tengah",
  country: "Indonesia",
  logo: "/logo.jpg",
  whatsappNumber: "6282222207157",
  whatsappFormatted: "+62 822-2220-7157",
  email: "abonkamera@gmail.com",
  currencySymbol: "Rp",
  currencyCode: "IDR",
  hours: "05.30 – 23.30 WIB",
  location: "Jl. Basudewa No. 08, Semarang, Jawa Tengah, Indonesia",
  links: {
    instagram: "https://www.instagram.com/abonkamerasemarang/",
    facebook: "https://www.facebook.com/Abonkamerasemarang/",
    whatsapp: "https://wa.me/6282222207157",
    googleMaps: "https://maps.app.goo.gl/7HZzQ2ZimfM1nJ3U8",
    priceListUrl: "https://bit.ly/PLAbonKameraSMG",
  },
  paymentInfo: {
    bcaAccount: "8035067082",
    bcaHolder: "Aji P.",
    bniAccount: "1997099905",
    bniHolder: "Aji P.",
  },
  terms: "Rentals require valid ID (KTP/SIM) and a deposit. All equipment must be checked upon pickup.",
};
